[primary]
hdrver = "Header version"
fitstype = "FITS definition for pulsar data files"
date = "File creation date (YYYY-MM-DDThh:mm:ss UTC)"
observer = "Observer name(s)"
projid = "Project name"
telescop = "Telescope name"
ant_x = "[m] Antenna ITRF X-coordinate (D)"
ant_y = "[m] Antenna ITRF Y-coordinate (D)"
ant_z = "[m] Antenna ITRF Z-coordinate (D)"
frontend = "Receiver ID"
ibeam = "Beam ID for multibeam systems"
nrcvr = "Number of receiver polarisation channels"
fd_poln = "LIN or CIRC"
fd_hand = "+/- 1. +1 is LIN:A=X,B=Y, CIRC:A=L,B=R (I)"
fd_sang = "[deg] FA of E vect for equal sig in A&B (E)"
fd_xyph = "[deg] Phase of A^* B for injected cal (E)"
backend = "Backend ID"
beconfig = "Backend configuration file name"
be_phase = "0/+1/-1 BE cross-phase:0 unknown,+/-1 std/rev"
be_dcc = "0/1 BE downconversion conjugation corrected"
be_delay = "Backend propn delay from digitiser input"
tcycle = "On-line cycle time (D)"
obs_mode = "(PSR, CAL, SEARCH)"
date-obs = "Date of observation (YYYY-MM-DDThh:mm:ss UTC)"
obsfreq = "[MHz] Centre frequency for observation"
obsbw = "[MHz] Bandwidth for observation"
obsnchan = "Number of frequency channels (original)"
chan_dm = "[cm-3 pc] DM used for on-line dedispersion"
pnt_id = "Name or ID for pointing ctr (multibeam feeds)"
src_name = "Source or scan ID"
coord_md = "Coordinate mode (J2000, GALACTIC, ECLIPTIC)"
equinox = "Equinox of coords (e.g. 2000.0)"
ra = "Right ascension (hh:mm:ss.ssss)"
dec = "Declination (-dd:mm:ss.sss)"
bmaj = "[deg] Beam major axis length"
bmin = "[deg] Beam minor axis length"
bpa = "[deg] Beam position angle"
stt_crd1 = "Start coord 1 (hh:mm:ss.sss or ddd.ddd)"
stt_crd2 = "Start coord 2 (-dd:mm:ss.sss or -dd.ddd)"
trk_mode = "Track mode (TRACK, SCANGC, SCANLAT)"
stp_crd1 = "Stop coord 1 (hh:mm:ss.sss or ddd.ddd)"
stp_crd2 = "Stop coord 2 (-dd:mm:ss.sss or -dd.ddd)"
scanlen = "[s] Requested scan length (E)"
fd_mode = "Feed track mode - FA, CPA, SPA, TPA"
fa_req = "[deg] Feed/Posn angle requested (E)"
cal_mode = "Cal mode (OFF, SYNC, EXT1, EXT2)"
cal_freq = "[Hz] Cal modulation frequency (E)"
cal_dcyc = "Cal duty cycle (E)"
cal_phs = "Cal phase (wrt start time) (E)"
cal_nphs = "Number of states in cal pulse (I)"
stt_imjd = "Start MJD (UTC days) (J - long integer)"
stt_smjd = "[s] Start time (sec past UTC 00h) (J)"
stt_offs = "[s] Start time offset (D)"
stt_lst = "[s] Start LST (D)"

[psrparam]
xtension = "***** Pulsar ephemeris *****"
bitpix = "N/A"
naxis = "2-dimensional binary table"
naxis1 = "width of table in bytes"
naxis2 = "number of rows in table"
pcount = "size of special data area"
gcount = "one data group (required keyword)"
tfields = "Number of fields per row"
ttype1 = "Text file stored row by row"
tform1 = "Allow 128 char per row"
extname = "Name of this binary table extension"
extver = "auto assigned by template parser"

[t2predict]
xtension = "***** Tempo2 Predictor *****"
bitpix = "N/A"
naxis = "2-dimensional binary table"
naxis1 = "width of table in bytes"
naxis2 = "number of rows in table"
pcount = "size of special data area"
gcount = "one data group (required keyword)"
tfields = "Number of fields per row"
ttype1 = "Text file stored row by row"
tform1 = "Allow 128 char per row"
extname = "Name of this binary table extension"
extver = "auto assigned by template parser"

[polyco]
xtension = "***** Polyco history *****"
bitpix = "N/A"
naxis = "2-dimensional binary table"
naxis1 = "width of table in bytes"
naxis2 = "number of rows in table"
pcount = "size of special data area"
gcount = "one data group (required keyword)"
tfields = "Number of fields per row"
ttype1 = "Polyco creation date and time (UTC)"
tform1 = "24-char string"
ttype2 = "Polyco version ID"
tform2 = "16-char string"
ttype3 = "Span of polyco block in min"
tform3 = "Integer"
ttype4 = "Nr of coefficients (<=15)"
tform4 = "Integer"
ttype5 = "Nr of blocks (rows) for this polyco"
tform5 = "Integer"
ttype6 = "Observatory code"
tform6 = "8-char string"
ttype7 = "Reference frequency for phase"
tform7 = "Double"
ttype8 = "Predicted pulse phase at observation start"
tform8 = "Double"
ttype9 = "Reference MJD"
tform9 = "Double"
ttype10 = "Reference phase"
tform10 = "Double"
ttype11 = "Zero-order pulsar frequency"
tform11 = "Double"
ttype12 = "Log_10 of polynomial fit rms error in periods"
tform12 = "Double"
ttype13 = "Polyco coefficients"
tform13 = "NCOEF doubles"
tunit7 = "units of field"
tunit11 = "units of field"
extname = "Name of this binary table extension"
extver = "auto assigned by template parser"


[history]
xtension = "***** Processing history *****"
bitpix = "N/A"
naxis = "2-dimensional binary table"
naxis1 = "width of table in bytes"
naxis2 = "number of rows in table"
pcount = "size of special data area"
gcount = "one data group (required keyword)"
tfields = "Number of fields per row"
ttype1 = "Processing date and time (UTC)"
tform1 = "24-char string"
ttype2 = "Processing program and command"
tform2 = "80-char string"
ttype3 = "Units (FluxDen/RefFlux/Jansky)"
tform3 = "8-char string"
ttype4 = "Polarisation identifier"
tform4 = "8-char string"
ttype5 = "Number of Sub-Integrations"
tform5 = "Integer"
ttype6 = "Number of polarisations"
tform6 = "Integer"
ttype7 = "Nr of bins per product (0 for SEARCH mode)"
tform7 = "Integer"
ttype8 = "Nr of bins per period"
tform8 = "Integer"
ttype9 = "Time per bin or sample"
tform9 = "Double"
ttype10 = "Band centre frequency (weighted)"
tform10 = "Double"
ttype11 = "Number of frequency channels"
tform11 = "Integer"
ttype12 = "Channel bandwidth"
tform12 = "Double"
ttype13 = "DM used for dedispersion"
tform13 = "Double"
ttype14 = "RM used for RM correction"
tform14 = "Double"
ttype15 = "Projection of receptors onto sky corrected"
tform15 = "Integer flag"
ttype16 = "Feed basis correction applied"
tform16 = "Integer flag"
ttype17 = "Backend correction applied"
tform17 = "Integer flag"
ttype18 = "RM correction applied"
tform18 = "Integer flag"
ttype19 = "Data dedispersed"
tform19 = "Integer flag"
ttype20 = "Dedispersion method"
tform20 = "32-char string"
ttype21 = "Scattered power correction method"
tform21 = "32-char string"
ttype22 = "Calibration method"
tform22 = "32-char string"
ttype23 = "Name of gain calibration file"
tform23 = "32-char string"
ttype24 = "RFI excision method"
tform24 = "32-char string"
ttype25 = "Auxiliary Faraday rotation model description"
tform25 = "32-char string"
ttype26 = "Auxiliary Faraday rotation corrected flag"
tform26 = "Integer flag"
ttype27 = "Auxiliary dispersion model description"
tform27 = "32-char string"
ttype28 = "Auxiliary dispersion corrected flag"
tform28 = "Integer flag"
tunit9 = "units of field"
tunit10 = "units of field"
tunit12 = "units of field"
tunit13 = "units of field"
tunit14 = "units of field"
extname = "Name of this binary table extension"
extver = "auto assigned by template parser"

[subint]
xtension = "***** Subintegration data *****"
naxis = "2-dimensional binary table"
naxis1 = "width of table in bytes"
naxis2 = "number of rows in table"
pcount = "size of special data area"
gcount = "one data group (required keyword)"
tfields = "Number of fields per row"
ttype1 = "Optionally used if INT_TYPE != TIME"
tform1 = "Double"
ttype2 = "Length of subintegration"
tform2 = "Double"
ttype3 = "Offset from Start of subint centre"
tform3 = "Double"
ttype4 = "LST at subint centre"
tform4 = "Double"
ttype5 = "RA (J2000) at subint centre"
tform5 = "Double"
ttype6 = "Dec (J2000) at subint centre"
tform6 = "Double"
ttype7 = "[deg] Gal longitude at subint centre"
tform7 = "Double"
ttype8 = "[deg] Gal latitude at subint centre"
tform8 = "Double"
ttype9 = "[deg] Feed angle at subint centre"
tform9 = "Float"
ttype10 = "[deg] Position angle  of feed at subint centre"
tform10 = "Float"
ttype11 = "[deg] Parallactic angle at subint centre"
tform11 = "Float"
ttype12 = "[deg] Telescope azimuth at subint centre"
tform12 = "Float"
ttype13 = "[deg] Telescope zenith angle at subint centre"
tform13 = "Float"
ttype14 = "additional DM (ionosphere, corona, etc.)"
tform14 = "Double"
ttype15 = "additional RM (ionosphere, corona, etc.)"
tform15 = "Double"
ttype16 = "[MHz] Centre frequency for each channel"
tform16 = "NCHAN doubles"
ttype17 = "Weights for each channel"
tform17 = "NCHAN floats"
ttype18 = "Data offset for each channel"
tform18 = "NCHAN*NPOL floats"
ttype19 = "Data scale factor (outval=dataval*scl + offs)"
tform19 = "NCHAN*NPOL floats"
ttype20 = "Subint data table"
tform20 = "I (Fold) or B (1-8 bit) Search"
int_type = "Time axis (TIME, BINSPHERI, BINLNGASC, etc)"
int_unit = "Unit of time axis (SEC, PHS (0-1), DEG)"
scale = "Intensity units (FluxDen/RefFlux/Jansky)"
pol_type = "Polarisation identifier (e.g., AABBCRCI, AA+BB)"
npol = "Nr of polarisations"
tbin = "[s] Time per bin or sample"
nbin = "Nr of bins (PSR/CAL mode; else 1)"
nbin_prd = "Nr of bins/pulse period (for gated data)"
phs_offs = "Phase offset of bin 0 for gated data"
nbits = "Nr of bits/datum (SEARCH mode data, else 1)"
zero_off = "Zero offset for SEARCH-mode data"
signint = "1 for signed ints in SEARCH-mode data, else 0"
nsuboffs = "Subint offset (Contiguous SEARCH-mode files)"
nchan = "Number of channels/sub-bands in this file"
chan_bw = "[MHz] Channel/sub-band width"
DM = "[cm-3 pc] DM for post-detection dedispersion"
RM = "[rad m-2] RM for post-detection deFaraday"
nchnoffs = "Channel/sub-band offset for split files"
nsblk = "Samples/row (SEARCH mode, else 1)"
nstot = "Total number of samples (SEARCH mode, else 1)"
epochs = "Epoch convention (VALID, MIDTIME, STT_MJD)"
tunit2 = "units of field"
tunit3 = "units of field"
tunit4 = "units of field"
tunit5 = "units of field"
tunit6 = "units of field"
tunit7 = "units of field"
tunit8 = "units of field"
tunit9 = "units of field"
tunit10 = "units of field"
tunit11 = "units of field"
tunit12 = "units of field"
tunit13 = "units of field"
tunit14 = "units of field"
tunit15 = "units of field"
tunit16 = "units of field"
tdim20 = "(NBIN,NCHAN,NPOL) or (NCHAN,NPOL,NSBLK*NBITS/8)"
tunit20 = "units of subint data"
extname = "Name of this binary table extension"
extver = "auto assigned by template parser"
